defmodule RacingOrg.Tracker.Pro.SecureTransport.GoldenTest do
  @moduledoc """
  DETERMINISTIC CROSS-IMPLEMENTATION GOLDEN — the definitive byte-compat proof.

  Loads `priv/secure_transport/handshake_kat.json` (generated by the SERVER on OTP 27
  and committed byte-identically to both repos) and, given the SAME fixed inputs
  (device + server Ed25519 keypairs, X25519 ephemerals for both sides, 32-byte
  server_nonce, session_epoch), reproduces every output byte on the DEVICE (OTP 28):
  the HELLO wire, the INIT wire, session_id, k_d2s, k_s2d, transcript_hash, and one
  sealed DATA frame. A matching backend test pins the server to the same file.
  """
  use ExUnit.Case, async: true

  alias RacingOrg.Tracker.Pro.SecureTransport.{Frame, Handshake}

  @golden_path Application.app_dir(:racing_org_tracker_pro, "priv/secure_transport/handshake_kat.json")

  setup_all do
    golden = @golden_path |> File.read!() |> Jason.decode!()
    %{inputs: golden["inputs"], outputs: golden["outputs"]}
  end

  defp hex(s), do: Base.decode16!(s, case: :lower)

  test "device reproduces the golden HELLO/INIT/keys/session_id/transcript/frame", %{
    inputs: inputs,
    outputs: outputs
  } do
    device_seed = hex(inputs["device_identity_seed"])
    device_pub = hex(inputs["device_identity_public"])
    server_seed = hex(inputs["server_identity_seed"])
    server_pub = hex(inputs["server_identity_public"])
    eph_d_priv = hex(inputs["eph_device_private"])
    eph_d_pub = hex(inputs["eph_device_public"])
    eph_s_priv = hex(inputs["eph_server_private"])
    eph_s_pub = hex(inputs["eph_server_public"])
    server_nonce = hex(inputs["server_nonce"])
    epoch = inputs["epoch"]
    device_id = inputs["device_id_utf8"]
    timestamp_ms = inputs["timestamp_ms"]
    plaintext = hex(inputs["frame_plaintext_hex"])

    # Re-derive the ephemeral publics from the fixed privates — must match the golden,
    # proving OTP 28 derives the same X25519 public from the same scalar as OTP 27.
    assert {^eph_d_pub, ^eph_d_priv} = :crypto.generate_key(:ecdh, :x25519, eph_d_priv)
    assert {^eph_s_pub, ^eph_s_priv} = :crypto.generate_key(:ecdh, :x25519, eph_s_priv)

    # Responder HELLO (device playing responder, with the fixed inputs).
    {:ok, hello_wire, rstate} =
      Handshake.responder_hello(
        server_identity_private: server_seed,
        server_identity_public: server_pub,
        device_identity_public: device_pub,
        ephemeral: {eph_s_pub, eph_s_priv},
        server_nonce: server_nonce,
        epoch: epoch
      )

    assert Base.encode16(hello_wire, case: :lower) == outputs["hello_wire"]

    # Initiator INIT (device's real role) — derives the session.
    {:ok, init_wire, dsession} =
      Handshake.initiator_init(hello_wire,
        device_identity_private: device_seed,
        device_identity_public: device_pub,
        server_identity_public: server_pub,
        device_id: device_id,
        ephemeral: {eph_d_pub, eph_d_priv},
        timestamp_ms: timestamp_ms,
        epoch: epoch
      )

    assert Base.encode16(init_wire, case: :lower) == outputs["init_wire"]

    # Responder finalize (cross-check both sides converge).
    {:ok, ssession} = Handshake.responder_finalize(rstate, init_wire)

    assert Base.encode16(dsession.session_id, case: :lower) == outputs["session_id"]
    assert Base.encode16(dsession.transcript_hash, case: :lower) == outputs["transcript_hash"]
    # initiator out = k_d2s, in = k_s2d.
    assert Base.encode16(dsession.out_key, case: :lower) == outputs["k_d2s"]
    assert Base.encode16(dsession.in_key, case: :lower) == outputs["k_s2d"]

    # Both sides agree.
    assert dsession.session_id == ssession.session_id
    assert dsession.out_key == ssession.in_key
    assert dsession.in_key == ssession.out_key

    # Seal one DATA frame on the DEVICE (initiator) at counter 0.
    assert dsession.send_counter == inputs["frame_counter"]
    {:ok, data_frame, _} = Frame.seal(dsession, plaintext)
    assert Base.encode16(data_frame, case: :lower) == outputs["data_frame"]

    # And the responder opens the golden frame back to the plaintext.
    assert {:ok, ^plaintext, _} = Frame.open(ssession, hex(outputs["data_frame"]))

    # P9-job-4: the STATELESS seal (the form the SessionHolder grant feeds the UDP
    # path) reproduces the SAME golden bytes from the explicit grant values, proving
    # byte-identity with `seal/2` and with the server's expected layout.
    assert {:ok, stateless_frame} =
             Frame.seal_with(
               dsession.session_id,
               dsession.epoch,
               inputs["frame_counter"],
               dsession.out_key,
               plaintext
             )

    assert Base.encode16(stateless_frame, case: :lower) == outputs["data_frame"]
    assert stateless_frame == data_frame

    # Loopback: the responder opens the statelessly-sealed frame back to plaintext.
    assert {:ok, ^plaintext, _} = Frame.open(ssession, stateless_frame)
  end
end
